# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  cmake-build:
    docker:
      # See: https://circleci.com/docs/configuration-reference/#executor-job
      - image: ubuntu:20.04
    steps:
      # See: https://circleci.com/docs/configuration-reference/#steps
      - checkout
      - run:
          name: Set noninteractive environment
          command: echo 'export DEBIAN_FRONTEND=noninteractive' >> $BASH_ENV
      - run:
          name: Install LittleCMS
          command: |
            apt-get update --assume-yes
            apt-get install --assume-yes --no-install-recommends cmake liblcms2-dev qt5-default
      - run:
          name: Build CMake project
          command: cmake . && make

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  cmake-build-workflow:
    jobs:
      - cmake-build
