name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CMake
        run: |
          brew update
          brew install cmake

      - name: Install MacPorts
        run: |
          curl -O https://distfiles.macports.org/MacPorts/MacPorts-2.7.3.tar.bz2
          tar xf MacPorts-2.7.3.tar.bz2
          cd MacPorts-2.7.3
          ./configure --prefix=/opt/local
          make
          sudo make install
          export PATH="/opt/local/bin:$PATH"

      - name: Install ECM
        run: |
          sudo port selfupdate
          sudo port install kde-frameworks-ecm

      - name: Build project
        run: |
          mkdir build
          cd build
          export CMAKE_PREFIX_PATH="/opt/local:$CMAKE_PREFIX_PATH"
          cmake ..
          cmake --build .

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
